/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CapaPresentacion;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class jifGestionVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form jmiGestionVentas
     */
    public jifGestionVentas() {
        initComponents();
        jpDetalleVenta.add(jmiSeleccionar);
        jtRegistroVentas.setComponentPopupMenu(jpDetalleVenta);
        cargarVentas();
        jmiSeleccionar.setText("Ver Detalle");
        setClosable(true);

    }
    
    private void cargarVentas() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID Venta");
            modelo.addColumn("Fecha");
            modelo.addColumn("Total");

            CapaDatos.VentaDAO dao = new CapaDatos.VentaDAO();
            List<CapaEntidad.Venta> ventas = dao.listarTodas();

            for (CapaEntidad.Venta v : ventas) {
                modelo.addRow(new Object[]{
                    v.getIdVenta(),
                    v.getFecha().toString(),
                    v.getTotal()
                });
            }

            jtRegistroVentas.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error al cargar ventas: " + e.getMessage());
        }
    }
    
    private void mostrarDetalleVenta(int idVenta) {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Producto");
            modelo.addColumn("Cantidad");
            modelo.addColumn("Precio Unitario");
            modelo.addColumn("Subtotal");

            CapaDatos.VentaDAO dao = new CapaDatos.VentaDAO();
            List<CapaEntidad.DetalleVenta> detalles = dao.listarDetallesPorVenta(idVenta);

            for (CapaEntidad.DetalleVenta d : detalles) {
                String nombreProducto = new CapaDatos.ProductoDAO().obtenerPorId(d.getIdProducto()).getNombre();
                double subtotal = d.getCantidad() * d.getPrecioUnitario();

                modelo.addRow(new Object[]{
                    nombreProducto,
                    d.getCantidad(),
                    d.getPrecioUnitario(),
                    subtotal
                });
            }

            jtDetalleVenta.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error al cargar detalle: " + e.getMessage());
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmiSeleccionar = new javax.swing.JMenuItem();
        jpDetalleVenta = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRegistroVentas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDetalleVenta = new javax.swing.JTable();

        jmiSeleccionar.setText("jMenuItem1");
        jmiSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSeleccionarActionPerformed(evt);
            }
        });

        jtRegistroVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtRegistroVentas);

        jtDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtDetalleVenta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila = jtRegistroVentas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Selecciona una venta.");
            return;
        }

        int idVenta = (int) jtRegistroVentas.getValueAt(fila, 0);  // ID está en la primera columna
        mostrarDetalleVenta(idVenta);
    }//GEN-LAST:event_jmiSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jmiSeleccionar;
    private javax.swing.JPopupMenu jpDetalleVenta;
    private javax.swing.JTable jtDetalleVenta;
    private javax.swing.JTable jtRegistroVentas;
    // End of variables declaration//GEN-END:variables
}
