/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

/**
 *
 * @author ASUS
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmiNUsuario = new javax.swing.JMenuItem();
        jmiGestionUsu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiProductos = new javax.swing.JMenuItem();
        jmiGestionProductos = new javax.swing.JMenuItem();
        jmiActualizarStock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiNuevaCategoria = new javax.swing.JMenuItem();
        jmiGestionCategoria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiNuevaVenta = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdPaneLayout = new javax.swing.GroupLayout(jdPane);
        jdPane.setLayout(jdPaneLayout);
        jdPaneLayout.setHorizontalGroup(
            jdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );
        jdPaneLayout.setVerticalGroup(
            jdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        jMenu2.setText("Usuarios");

        jmiNUsuario.setText("Nuevo Usuario");
        jMenu2.add(jmiNUsuario);

        jmiGestionUsu.setText("Gestionar Usuarios");
        jMenu2.add(jmiGestionUsu);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Productos");

        jmiProductos.setText("Nuevo Producto");
        jmiProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiProductos);

        jmiGestionProductos.setText("Gestionar Productos");
        jmiGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionProductosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiGestionProductos);

        jmiActualizarStock.setText("Actualizar Stock");
        jmiActualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiActualizarStockActionPerformed(evt);
            }
        });
        jMenu1.add(jmiActualizarStock);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Categoria");

        jmiNuevaCategoria.setText("Nueva  categoria");
        jmiNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevaCategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiNuevaCategoria);

        jmiGestionCategoria.setText("Gestionar categoria");
        jmiGestionCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionCategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiGestionCategoria);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Venta");

        jmiNuevaVenta.setText("Nueva Venta");
        jmiNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevaVentaActionPerformed(evt);
            }
        });
        jMenu4.add(jmiNuevaVenta);

        jMenuItem5.setText("Gestionar Ventas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Compra");

        jmiCompra.setText("Nueva Compra");
        jmiCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCompraActionPerformed(evt);
            }
        });
        jMenu5.add(jmiCompra);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductosActionPerformed
        // TODO add your handling code here:
        jifProducto jif1=new jifProducto();
        jdPane.add(jif1);
        jif1.setVisible(true);
    }//GEN-LAST:event_jmiProductosActionPerformed

    private void jmiGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionProductosActionPerformed
        // TODO add your handling code here:
        jifGestionProductos jif1 = new jifGestionProductos();
        jdPane.add(jif1);
        jif1.setVisible(true);
    }//GEN-LAST:event_jmiGestionProductosActionPerformed

    private void jmiActualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiActualizarStockActionPerformed
        // TODO add your handling code here:
        jifActualizarStock jif1 = new jifActualizarStock();
        jdPane.add(jif1);
        jif1.setVisible(true);
    }//GEN-LAST:event_jmiActualizarStockActionPerformed

    private void jmiNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevaCategoriaActionPerformed
        // TODO add your handling code here:
        jifCategoria jif1 = new jifCategoria();
        jdPane.add(jif1);
        jif1.setVisible(true);
        
    }//GEN-LAST:event_jmiNuevaCategoriaActionPerformed

    private void jmiGestionCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionCategoriaActionPerformed
        // TODO add your handling code here:
        jifGestionCategoria jif1 = new jifGestionCategoria();
        jdPane.add(jif1);
        jif1.setVisible(true);
    }//GEN-LAST:event_jmiGestionCategoriaActionPerformed

    private void jmiNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevaVentaActionPerformed
        // TODO add your handling code here:
        jifVenta jif = new jifVenta();
        jdPane.add(jif);
        jif.setVisible(true);
    }//GEN-LAST:event_jmiNuevaVentaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jifGestionVentas jif = new jifGestionVentas();
        jdPane.add(jif);
        jif.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmiCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCompraActionPerformed
        // TODO add your handling code here:
        jifCompra jif = new jifCompra();
        jdPane.add(jif);
        jif.setVisible(true);
    }//GEN-LAST:event_jmiCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JDesktopPane jdPane;
    private javax.swing.JMenuItem jmiActualizarStock;
    private javax.swing.JMenuItem jmiCompra;
    private javax.swing.JMenuItem jmiGestionCategoria;
    private javax.swing.JMenuItem jmiGestionProductos;
    private javax.swing.JMenuItem jmiGestionUsu;
    private javax.swing.JMenuItem jmiNUsuario;
    private javax.swing.JMenuItem jmiNuevaCategoria;
    private javax.swing.JMenuItem jmiNuevaVenta;
    private javax.swing.JMenuItem jmiProductos;
    // End of variables declaration//GEN-END:variables
}
